version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: neural_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  app:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    command: ["python", "-c", "import neural_sdk; print('Neural SDK ready with env')"]

volumes:
  redis_data:

