[project]
name = "kalshi-agentic-agent"
version = "0.1.0"
description = "Autonomous Agent for Trading Sport Event Contracts on the Kalshi Platform"
requires-python = ">=3.10, <3.13"
dependencies = [
    "agentuity>=0.0.103",
    "kalshi-python>=2.0.0",
    "websockets>=11.0",
    "websocket-client>=1.6.0",
    "aiohttp>=3.9.0",
    "pydantic>=2.5.0",
    "python-dotenv>=1.0.0",
    "numpy>=1.24.0",
    "pandas>=2.1.0",
    "scipy>=1.11.0",
    "httpx>=0.25.0",
    "rich>=13.7.0",
    "click>=8.1.7",
    "pyyaml>=6.0.1",
    "pytz>=2023.3",
    "python-dateutil>=2.8.2",
    "nest-asyncio>=1.5.8",
    "cryptography>=41.0.0",
    "e2b>=0.17.0",
]

[tool.setuptools]
packages = ["agents", "agentuity_agents", "tools", "kalshi_web_infra"]

[tool.setuptools.package-data]
"*" = ["*.py"]
