"""
Base classes and abstractions for Neural SDK Strategy Framework.

This module provides the foundational classes for building trading strategies
that can analyze Kalshi markets and generate actionable trading signals.
"""

import asyncio
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple, Any, Union
from enum import Enum
import numpy as np

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Types of trading signals."""
    BUY_YES = "buy_yes"
    BUY_NO = "buy_no"
    SELL_YES = "sell_yes"
    SELL_NO = "sell_no"
    HOLD = "hold"
    CLOSE_POSITION = "close_position"


class PositionAction(Enum):
    """Position management actions."""
    OPEN_LONG = "open_long"
    OPEN_SHORT = "open_short"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"
    HOLD = "hold"
    REDUCE_SIZE = "reduce_size"
    INCREASE_SIZE = "increase_size"


@dataclass
class StrategyConfig:
    """
    Configuration parameters for trading strategies.
    
    This dataclass defines common configuration that all strategies
    should support for consistent behavior.
    """
    # Risk management
    max_position_size: float = 0.10  # Max % of capital per position
    max_portfolio_exposure: float = 0.50  # Max total exposure
    stop_loss_pct: float = 0.20  # Stop loss percentage
    take_profit_pct: float = 0.50  # Take profit percentage
    
    # Signal generation
    min_confidence: float = 0.60  # Minimum confidence to act
    min_edge: float = 0.03  # Minimum edge to trade
    lookback_hours: int = 24  # Hours of historical data
    
    # Position sizing
    use_kelly_criterion: bool = True
    max_kelly_fraction: float = 0.25  # Maximum Kelly fraction
    fixed_position_size: Optional[float] = None  # Fixed size if not using Kelly
    
    # Trading constraints
    max_trades_per_day: int = 10
    min_time_between_trades: int = 300  # Seconds
    markets_blacklist: List[str] = field(default_factory=list)
    
    # Strategy-specific parameters
    strategy_params: Dict[str, Any] = field(default_factory=dict)
    
    def validate(self) -> None:
        """Validate configuration parameters."""
        if not 0 < self.max_position_size <= 1:
            raise ValueError(f"max_position_size must be between 0 and 1, got {self.max_position_size}")
        
        if not 0 < self.min_confidence <= 1:
            raise ValueError(f"min_confidence must be between 0 and 1, got {self.min_confidence}")
        
        if self.min_edge < 0:
            raise ValueError(f"min_edge must be non-negative, got {self.min_edge}")


@dataclass 
class Signal:
    """
    Trading signal generated by a strategy.
    
    Encapsulates all information needed to make a trading decision
    including signal type, sizing, and risk management.
    """
    # Core signal information
    signal_type: SignalType
    market_id: str
    timestamp: datetime
    
    # Signal strength and confidence
    confidence: float  # 0 to 1
    edge: float  # Estimated edge
    expected_value: float  # Expected value of trade
    
    # Position sizing
    recommended_size: float  # Fraction of capital
    max_contracts: int  # Maximum contracts to trade
    
    # Risk management
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None
    max_hold_time: Optional[timedelta] = None
    
    # Supporting information
    reason: str = ""  # Human readable reason
    analysis_components: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    @property
    def is_actionable(self) -> bool:
        """Check if signal is actionable (not HOLD)."""
        return self.signal_type != SignalType.HOLD
    
    @property
    def is_buy_signal(self) -> bool:
        """Check if signal is a buy signal."""
        return self.signal_type in [SignalType.BUY_YES, SignalType.BUY_NO]
    
    @property
    def is_sell_signal(self) -> bool:
        """Check if signal is a sell signal."""
        return self.signal_type in [SignalType.SELL_YES, SignalType.SELL_NO]
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary."""
        return {
            'signal_type': self.signal_type.value,
            'market_id': self.market_id,
            'timestamp': self.timestamp.isoformat(),
            'confidence': self.confidence,
            'edge': self.edge,
            'expected_value': self.expected_value,
            'recommended_size': self.recommended_size,
            'max_contracts': self.max_contracts,
            'stop_loss_price': self.stop_loss_price,
            'take_profit_price': self.take_profit_price,
            'max_hold_time': self.max_hold_time.total_seconds() if self.max_hold_time else None,
            'reason': self.reason,
            'analysis_components': self.analysis_components,
            'metadata': self.metadata
        }


@dataclass
class StrategyResult:
    """
    Result of strategy analysis on a market.
    
    Contains the generated signal plus additional analysis and diagnostics.
    """
    strategy_name: str
    market_id: str
    timestamp: datetime
    signal: Signal
    
    # Performance tracking
    analysis_time_ms: float = 0
    data_quality_score: float = 1.0
    
    # Diagnostics
    warnings: List[str] = field(default_factory=list)
    debug_info: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert result to dictionary."""
        return {
            'strategy_name': self.strategy_name,
            'market_id': self.market_id,
            'timestamp': self.timestamp.isoformat(),
            'signal': self.signal.to_dict(),
            'analysis_time_ms': self.analysis_time_ms,
            'data_quality_score': self.data_quality_score,
            'warnings': self.warnings,
            'debug_info': self.debug_info
        }


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    This class defines the interface that all trading strategies must implement,
    providing a consistent framework for signal generation and risk management.
    """
    
    def __init__(
        self, 
        name: str,
        config: Optional[StrategyConfig] = None
    ):
        """
        Initialize strategy.
        
        Args:
            name: Strategy name
            config: Strategy configuration
        """
        self.name = name
        self.config = config or StrategyConfig()
        self.config.validate()
        
        # State tracking
        self._initialized = False
        self._last_trade_time = {}  # Per market
        self._position_tracker = {}  # Current positions
        self._trade_count_today = 0
        
        # Performance tracking
        self._signals_generated = 0
        self._successful_trades = 0
        self._total_pnl = 0.0
        
        logger.info(f"Strategy '{self.name}' initialized")
    
    @abstractmethod
    async def initialize(self) -> None:
        """
        Initialize the strategy.
        
        This method should perform any setup required before the strategy
        can generate signals, such as loading models or historical data.
        """
        pass
    
    @abstractmethod
    async def analyze_market(
        self,
        market_id: str,
        market_data: Dict[str, Any],
        context: Optional[Dict[str, Any]] = None
    ) -> StrategyResult:
        """
        Analyze a market and generate a trading signal.
        
        Args:
            market_id: Market identifier
            market_data: Current market data and state
            context: Additional context (portfolio, external data, etc.)
            
        Returns:
            StrategyResult with trading signal
        """
        pass
    
    @abstractmethod
    def get_required_data(self) -> List[str]:
        """
        Get list of required data fields for analysis.
        
        Returns:
            List of required field names
        """
        pass
    
    async def batch_analyze(
        self,
        markets_data: Dict[str, Dict[str, Any]],
        context: Optional[Dict[str, Any]] = None
    ) -> List[StrategyResult]:
        """
        Analyze multiple markets in batch.
        
        Args:
            markets_data: Dictionary mapping market_id to market data
            context: Shared context for all markets
            
        Returns:
            List of StrategyResults
        """
        if not self._initialized:
            await self.initialize()
            self._initialized = True
        
        tasks = []
        for market_id, market_data in markets_data.items():
            if self._should_analyze_market(market_id, market_data):
                task = self.analyze_market(market_id, market_data, context)
                tasks.append(task)
        
        results = await asyncio.gather(*tasks, return_exceptions=True)
        
        # Filter out exceptions and log errors
        valid_results = []
        for result in results:
            if isinstance(result, Exception):
                logger.error(f"Error analyzing market: {result}")
            else:
                valid_results.append(result)
        
        return valid_results
    
    def _should_analyze_market(
        self,
        market_id: str,
        market_data: Dict[str, Any]
    ) -> bool:
        """
        Check if market should be analyzed.
        
        Args:
            market_id: Market identifier
            market_data: Market data
            
        Returns:
            True if market should be analyzed
        """
        # Check blacklist
        if market_id in self.config.markets_blacklist:
            return False
        
        # Check if too soon since last trade
        if market_id in self._last_trade_time:
            time_since_last = (
                datetime.now() - self._last_trade_time[market_id]
            ).total_seconds()
            if time_since_last < self.config.min_time_between_trades:
                return False
        
        # Check daily trade limit
        if self._trade_count_today >= self.config.max_trades_per_day:
            return False
        
        # Check if market is active
        market_status = market_data.get('status', 'unknown')
        if market_status not in ['open', 'active']:
            return False
        
        return True
    
    def calculate_position_size(
        self,
        signal: Signal,
        current_capital: float,
        current_positions: Optional[Dict[str, float]] = None
    ) -> int:
        """
        Calculate optimal position size for a signal.
        
        Args:
            signal: Trading signal
            current_capital: Available capital
            current_positions: Current position sizes by market
            
        Returns:
            Number of contracts to trade
        """
        current_positions = current_positions or {}
        
        # Check portfolio exposure
        total_exposure = sum(abs(pos) for pos in current_positions.values())
        if total_exposure >= self.config.max_portfolio_exposure:
            return 0
        
        # Calculate base position size
        if self.config.use_kelly_criterion and signal.edge > 0:
            from neural.kalshi.fees import calculate_kelly_fraction
            
            # Estimate market price from signal metadata
            market_price = signal.metadata.get('market_price', 0.5)
            
            kelly_size = calculate_kelly_fraction(
                market_price + signal.edge,
                market_price,
                self.config.max_kelly_fraction
            )
            position_dollars = current_capital * kelly_size
        else:
            # Fixed position sizing
            if self.config.fixed_position_size:
                position_dollars = current_capital * self.config.fixed_position_size
            else:
                position_dollars = current_capital * signal.recommended_size
        
        # Apply maximum position size constraint
        max_position_dollars = current_capital * self.config.max_position_size
        position_dollars = min(position_dollars, max_position_dollars)
        
        # Convert to contracts
        market_price = signal.metadata.get('market_price', 0.5)
        if market_price <= 0:
            return 0
        
        contracts = int(position_dollars / market_price)
        
        # Apply signal's max contracts constraint
        contracts = min(contracts, signal.max_contracts)
        
        return max(0, contracts)
    
    def update_position(
        self,
        market_id: str,
        action: PositionAction,
        size: int,
        price: float
    ) -> None:
        """
        Update position tracking.
        
        Args:
            market_id: Market identifier
            action: Position action taken
            size: Number of contracts
            price: Execution price
        """
        if market_id not in self._position_tracker:
            self._position_tracker[market_id] = {
                'size': 0,
                'avg_price': 0,
                'unrealized_pnl': 0
            }
        
        position = self._position_tracker[market_id]
        
        if action in [PositionAction.OPEN_LONG, PositionAction.INCREASE_SIZE]:
            # Calculate new average price
            current_value = position['size'] * position['avg_price']
            new_value = size * price
            total_size = position['size'] + size
            
            if total_size > 0:
                position['avg_price'] = (current_value + new_value) / total_size
            position['size'] = total_size
            
        elif action in [PositionAction.CLOSE_LONG, PositionAction.REDUCE_SIZE]:
            position['size'] = max(0, position['size'] - size)
            if position['size'] == 0:
                position['avg_price'] = 0
        
        # Update last trade time
        self._last_trade_time[market_id] = datetime.now()
        self._trade_count_today += 1
    
    def get_current_position(self, market_id: str) -> Dict[str, float]:
        """
        Get current position for a market.
        
        Args:
            market_id: Market identifier
            
        Returns:
            Dictionary with position information
        """
        return self._position_tracker.get(market_id, {
            'size': 0,
            'avg_price': 0,
            'unrealized_pnl': 0
        })
    
    def reset_daily_counters(self) -> None:
        """Reset daily trade counters."""
        self._trade_count_today = 0
        logger.info(f"Strategy '{self.name}' daily counters reset")
    
    def get_performance_stats(self) -> Dict[str, Any]:
        """
        Get strategy performance statistics.
        
        Returns:
            Dictionary with performance metrics
        """
        win_rate = (
            self._successful_trades / max(1, self._signals_generated) 
            if self._signals_generated > 0 else 0
        )
        
        return {
            'strategy_name': self.name,
            'signals_generated': self._signals_generated,
            'successful_trades': self._successful_trades,
            'win_rate': win_rate,
            'total_pnl': self._total_pnl,
            'trades_today': self._trade_count_today,
            'active_positions': len([
                pos for pos in self._position_tracker.values() 
                if pos.get('size', 0) != 0
            ]),
            'config': self.config.__dict__
        }
    
    async def cleanup(self) -> None:
        """
        Cleanup strategy resources.
        
        This method should release any resources held by the strategy.
        """
        self._initialized = False
        logger.info(f"Strategy '{self.name}' cleaned up")
    
    def __repr__(self) -> str:
        """String representation."""
        return f"{self.__class__.__name__}(name='{self.name}')"


class StrategyManager:
    """
    Manages multiple trading strategies and coordinates their execution.
    
    This class handles strategy lifecycle, signal aggregation, and
    position management across multiple strategies.
    """
    
    def __init__(self):
        """Initialize strategy manager."""
        self.strategies: Dict[str, BaseStrategy] = {}
        self.active_signals: List[Signal] = []
        self.signal_history: List[Signal] = []
        self.max_history_size = 10000
        
    def add_strategy(self, strategy: BaseStrategy) -> None:
        """
        Add a strategy to the manager.
        
        Args:
            strategy: Strategy to add
        """
        self.strategies[strategy.name] = strategy
        logger.info(f"Added strategy: {strategy.name}")
    
    def remove_strategy(self, strategy_name: str) -> None:
        """
        Remove a strategy from the manager.
        
        Args:
            strategy_name: Name of strategy to remove
        """
        if strategy_name in self.strategies:
            del self.strategies[strategy_name]
            logger.info(f"Removed strategy: {strategy_name}")
    
    async def analyze_markets(
        self,
        markets_data: Dict[str, Dict[str, Any]],
        context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, List[StrategyResult]]:
        """
        Run all strategies on market data.
        
        Args:
            markets_data: Market data by market_id
            context: Additional context
            
        Returns:
            Dictionary mapping strategy name to results
        """
        results = {}
        
        # Run all strategies in parallel
        tasks = []
        for strategy_name, strategy in self.strategies.items():
            task = strategy.batch_analyze(markets_data, context)
            tasks.append((strategy_name, task))
        
        # Gather results
        for strategy_name, task in tasks:
            try:
                strategy_results = await task
                results[strategy_name] = strategy_results
            except Exception as e:
                logger.error(f"Error in strategy {strategy_name}: {e}")
                results[strategy_name] = []
        
        # Update signal history
        for strategy_results in results.values():
            for result in strategy_results:
                self.signal_history.append(result.signal)
        
        # Trim history if needed
        if len(self.signal_history) > self.max_history_size:
            self.signal_history = self.signal_history[-self.max_history_size:]
        
        return results
    
    def get_consolidated_signals(
        self,
        results: Dict[str, List[StrategyResult]]
    ) -> Dict[str, List[Signal]]:
        """
        Consolidate signals by market.
        
        Args:
            results: Strategy results
            
        Returns:
            Dictionary mapping market_id to list of signals (excludes markets with only HOLD signals)
        """
        consolidated = {}
        
        for strategy_results in results.values():
            for result in strategy_results:
                if result.signal.is_actionable:
                    market_id = result.market_id
                    if market_id not in consolidated:
                        consolidated[market_id] = []
                    consolidated[market_id].append(result.signal)
        
        return consolidated
    
    def get_manager_stats(self) -> Dict[str, Any]:
        """
        Get strategy manager statistics.
        
        Returns:
            Dictionary with manager stats
        """
        return {
            'num_strategies': len(self.strategies),
            'strategy_names': list(self.strategies.keys()),
            'signal_history_size': len(self.signal_history),
            'active_signals': len(self.active_signals),
            'individual_stats': {
                name: strategy.get_performance_stats()
                for name, strategy in self.strategies.items()
            }
        }
