# Production Environment Configuration
# CRITICAL: This configuration is for LIVE TRADING with REAL MONEY

name: "Production"
environment: "production"
redis_db: 0
redis_prefix: "prod:"

api_endpoints:
  kalshi: "https://api.kalshi.com"
  odds: "https://api.theoddsapi.com/v4"
  sportsdata: "https://api.sportsdata.io/v3/nfl"
  twitter: "https://api.twitter.com/2"

rate_limits:
  kalshi: 100
  odds: 50
  sportsdata: 100
  twitter: 300

# Safety and Security
safety_checks: true
require_confirmation: true
require_mfa: true

# Allowed Operations
allowed_operations:
  - "place_order"
  - "cancel_order"
  - "get_positions"
  - "get_markets"
  - "get_account"
  - "analyze_market"
  - "calculate_kelly"

# Restricted Operations
restricted_operations:
  - "delete_all_data"
  - "reset_account"
  - "modify_system_config"
  - "bypass_risk_checks"

# Data Management
data_retention_hours: 720  # 30 days
backup_enabled: true
backup_frequency_hours: 24

# Trading Limits
max_position_size: 0.05  # 5% of portfolio
max_daily_trades: 20
max_concurrent_positions: 10
max_order_value: 1000.0
min_order_value: 1.0

# Risk Management
stop_loss_percentage: 0.10
max_drawdown_percentage: 0.20
position_sizing_method: "kelly_fraction"
kelly_fraction: 0.25

# Logging and Monitoring
enable_logging: true
log_level: "INFO"
telemetry_enabled: true
alert_enabled: true
alert_channels:
  - "email"
  - "slack"

# Feature Flags
features:
  auto_trading: true
  paper_trading: false
  backtesting: false
  synthetic_data: false
  debug_mode: false
  performance_profiling: true
  real_time_analytics: true
  emergency_stop: true
  
# Monitoring Thresholds
monitoring:
  latency_threshold_ms: 1000
  error_rate_threshold: 0.01
  memory_threshold_gb: 4
  cpu_threshold_percent: 80