# Sandbox Environment Configuration
# For testing with demo APIs and safe experimentation

name: "Sandbox"
environment: "sandbox"
redis_db: 2
redis_prefix: "sandbox:"

api_endpoints:
  kalshi: "https://demo-api.kalshi.co"
  odds: "https://api.theoddsapi.com/v4"
  sportsdata: "https://api.sportsdata.io/v3/nfl"
  twitter: "https://api.twitter.com/2"

rate_limits:
  kalshi: 500
  odds: 200
  sportsdata: 200
  twitter: 500

# Safety and Security
safety_checks: true
require_confirmation: false
require_mfa: false

# Allowed Operations
allowed_operations:
  - "*"  # All operations allowed in sandbox

# Restricted Operations
restricted_operations:
  - "delete_production_data"
  - "modify_production_config"

# Data Management
data_retention_hours: 24  # 1 day retention
backup_enabled: false
backup_frequency_hours: 0

# Trading Limits (Moderate for sandbox)
max_position_size: 0.20  # 20% of portfolio
max_daily_trades: 100
max_concurrent_positions: 50
max_order_value: 10000.0
min_order_value: 0.10

# Risk Management
stop_loss_percentage: 0.20
max_drawdown_percentage: 0.40
position_sizing_method: "kelly_fraction"
kelly_fraction: 0.50

# Logging and Monitoring
enable_logging: true
log_level: "DEBUG"
telemetry_enabled: false
alert_enabled: false
alert_channels: []

# Feature Flags
features:
  auto_trading: true
  paper_trading: true
  backtesting: true
  synthetic_data: false
  debug_mode: true
  performance_profiling: true
  real_time_analytics: true
  emergency_stop: true
  sandbox_mode: true
  api_mocking: true
  
# Sandbox Specific Settings
sandbox:
  reset_daily: true
  demo_balance: 10000.0
  unlimited_retries: true
  skip_authentication: false
  mock_latency_ms: 100
  
# Monitoring Thresholds
monitoring:
  latency_threshold_ms: 2000
  error_rate_threshold: 0.05
  memory_threshold_gb: 4
  cpu_threshold_percent: 90