# Training Environment Configuration
# For agent training with synthetic data

name: "Training"
environment: "training"
redis_db: 3
redis_prefix: "training:"

api_endpoints:
  kalshi: "http://localhost:8000/mock/kalshi"
  odds: "http://localhost:8001/mock/odds"
  sportsdata: "http://localhost:8002/mock/sportsdata"
  twitter: "http://localhost:8003/mock/twitter"

rate_limits:
  kalshi: 10000
  odds: 10000
  sportsdata: 10000
  twitter: 10000

# Safety and Security
safety_checks: false
require_confirmation: false
require_mfa: false

# Allowed Operations
allowed_operations:
  - "*"  # All operations allowed in training

# Restricted Operations
restricted_operations: []  # No restrictions in training

# Data Management
data_retention_hours: 4  # Short retention for training data
backup_enabled: false
backup_frequency_hours: 0

# Trading Limits (Relaxed for training)
max_position_size: 1.0  # 100% allowed for training
max_daily_trades: 10000
max_concurrent_positions: 1000
max_order_value: 1000000.0
min_order_value: 0.01

# Risk Management (Configurable for training)
stop_loss_percentage: 0.50
max_drawdown_percentage: 1.0
position_sizing_method: "kelly_fraction"
kelly_fraction: 1.0  # Full Kelly for training experiments

# Logging and Monitoring
enable_logging: true
log_level: "DEBUG"
telemetry_enabled: false
alert_enabled: false
alert_channels: []

# Feature Flags
features:
  auto_trading: true
  paper_trading: true
  backtesting: true
  synthetic_data: true
  debug_mode: true
  performance_profiling: true
  real_time_analytics: false
  emergency_stop: false
  training_mode: true
  exploration_mode: true
  replay_mode: true
  
# Training Specific Settings
training:
  scenario_generation: true
  adaptive_difficulty: true
  performance_tracking: true
  decision_replay: true
  confidence_calibration: true
  memory_system: true
  batch_size: 32
  learning_rate: 0.001
  
# Synthetic Data Settings
synthetic_data:
  generation_enabled: true
  realistic_timing: true
  market_reaction_simulation: true
  price_impact_modeling: true
  volatility_injection: true
  
# Monitoring Thresholds (Relaxed for training)
monitoring:
  latency_threshold_ms: 5000
  error_rate_threshold: 0.10
  memory_threshold_gb: 8
  cpu_threshold_percent: 95